sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  - composer install
after_script:
  - CODECLIMATE_REPO_TOKEN=b92d0a7221ef3258c0b20c5e970be1f429757ab324d9decff0cf5810e63eb3a6 ./vendor/bin/test-reporter
